### PR TITLE
ARGH! Forgot to commit the fsproj changes

### PR DESCRIPTION
**Pull request by frankhale**
- Forgot to click save after I deleted the default Web API controller.
LOL!

### CODE REVIEW

**Comment by ybotspawn** [comment]
Fail!

**Comment by frankhale** [comment]
I deleted the file then promptly git committed it. Totally forgot to save the project so that the fsproj would know the change was made. MY BAD DOG!

**Comment by ybotspawn** [comment]
Lol between the two of us one of us is going to rant apeshit about the damn
fsproj file before this is over.

**Comment by frankhale** [comment]
Yes we are. In this case I didn't have to hand edit. I deleted the file in Visual Studio and forgot to click save. Adding new files is another thing entirely, LOL! Escpecially with the hacked folder support.

**Pull request merged**
